import { z } from 'zod'

export const ItemFormSchema = z.object({
    id: z.string().min(1, { message: 'ID is required.' }).default('create'),
    code: z.string().min(1, { message: 'Code is required.' }).default(''),
    name: z.string().min(1, { message: 'Name is required.' }).default(''),
    barcode: z.string().nullish(),
    active: z.boolean().default(true),
    typeId: z.string().min(1, { message: 'Item type is required.' }).default(''),
    categoryId: z.string().nullish(),
    brandId: z.string().nullish(),
    details: z.string().nullish(),
    manufacturerId: z.string().nullish(),
    manufacturerCode: z.string().nullish(),
    divisionId: z.string().nullish(),
    familyId: z.string().nullish(),
    genericTypeId: z.string().nullish(),
    genericName: z.string().nullish(),
    dosage: z.string().nullish(),
    indication: z.string().nullish(),
    isInventoryItem: z.boolean().default(true),
    preventNegativeQty: z.boolean().default(true),
    stockOutWarning: z.boolean().default(true),
    netWeight: z.number().nullish(),
    grossWeight: z.number().nullish(),
    unitVolume: z.number().nullish(),
    autoCreateNewBatch: z.boolean().default(false),
    hasSerialNo: z.boolean().default(false),
    hasLotNo: z.boolean().default(false),
    hasExpiryDate: z.boolean().default(false),
    expirationDays: z.number().nullish(),
    costingMethodId: z.string().nullish(),
    standardCost: z.number().nonnegative().default(0),
    unitCost: z.number().nonnegative().default(0),
    isPurchaseItem: z.boolean().default(true),
    purchaseUOMId: z.string().nullish(),
    purchaseTaxTypeId: z.string().nullish(),
    principalId: z.string().nullish(),
    salesUOMId: z.string().nullish(),
    salesTaxTypeId: z.string().nullish(),
    unitPrice: z.number().nonnegative().default(0),
    markup: z.number().nonnegative().default(0),
    standardPrice: z.number().nonnegative().default(0),
    salesItemName: z.string().nullish(),
    isSaleableItem: z.boolean().default(true),
    allowSalesDiscount: z.boolean().default(true),
    allowSCPWD: z.boolean().default(true),
    hasServiceCharge: z.boolean().default(true),
    scPercentage: z.number().nullish(),
    leadTime: z.number().nullish(),
    safetyStock: z.number().nullish(),
    maxInv: z.number().nullish(),
    reOrderPoint: z.number().nullish(),
    reStockQty: z.number().nullish(),
    minOrder: z.number().nullish(),
    maxOrder: z.number().nullish(),
    temp: z.string().nullish(), // ---> TEMPORARY SHOULD BE REMOVED. ITO YUNG MGA FIELDS NA AUTO COMPUTED SA FORM
})

export const ItemPostSchema = ItemFormSchema.omit({ id: true })
export const ItemUpdateSchema = ItemFormSchema
export const ItemDeleteSchema = z.object({ id: z.string() })
